### ISSUE TITLE
Man kan ikke tilføje lokaler

### ISSUE THREAD

**Issue by KristianKlode** [NCLI/revyorganisator#10]
1. Går ind på hjemmeside.  
2. Klikker på øvedag. 
3. Klikker på tilføj lokale. 
4. Får fejlbesked 404.

Forventning:
1. Går ind på hjemmeside.  
2. Klikker på øvedag. 
3. Klikker på tilføj lokale. 
4. Bliver præsenteret for en tekstboks hvor man kan indtaste lokalenavn

**Comment by NCLI** [comment]
Fixed by commit ab62956.
