### ISSUE TITLE
Man kan ikke tilføje det samme lokale på to forskellige dage

### ISSUE THREAD

**Issue by SofieBugge** [NCLI/revyorganisator#24]
Det er ikke muligt at tilføje det samme lokale på to forskellige dage. Dette skal være en mulighed.

Forventning:

1. Brugeren åbner /scheduler.
2. Brugeren vælger en øvedag.
3. Brugeren klikker på knappen "Tilføj lokale".
4. Der kommer en liste over tidligere lokaler, som brugeren kan vælge. Det er også muligt at skrive et helt nyt lokale ind.

**Comment by NCLI** [comment]
This was fixed in version-0.2.
